[level]
music = "sound/vt.vgm"
spawn = [
	{ x=-5, y=73 }
]

[objects.static]
breakable_block = [
	{ path="maps/vt/block3.png", particle_path="maps/vt/rock.png", drops_ring=true, tile_x=34, tile_y=2 },
	{ path="maps/vt/block3.png", particle_path="maps/vt/rock.png", drops_ring=true, tile_x=45, tile_y=12 },
	{ path="maps/vt/block3.png", particle_path="maps/vt/rock.png", drops_ring=true, tile_x=45, tile_y=13 },
	{ path="maps/vt/block1.png", particle_path="maps/vt/rock.png", tile_x=63, tile_y=1 },
	{ path="maps/vt/block1.png", particle_path="maps/vt/rock.png", tile_x=63, tile_y=2 },
	{ path="maps/vt/block1.png", particle_path="maps/vt/rock.png", tile_x=63, tile_y=3 },
	{ path="maps/vt/block2.png", particle_path="maps/vt/rock.png", tile_x=64, tile_y=1 },
	{ path="maps/vt/block2.png", particle_path="maps/vt/rock.png", tile_x=64, tile_y=2 },
	{ path="maps/vt/block2.png", particle_path="maps/vt/rock.png", tile_x=64, tile_y=3 },
	{ path="maps/vt/block3.png", particle_path="maps/vt/rock.png", drops_ring=true, tile_x=70, tile_y=13 },
	{ path="maps/vt/block3.png", particle_path="maps/vt/rock.png", drops_ring=true, tile_x=70, tile_y=14 },
	{ path="maps/vt/block1.png", particle_path="maps/vt/rock.png", tile_x=80, tile_y=13 },
	{ path="maps/vt/block1.png", particle_path="maps/vt/rock.png", tile_x=80, tile_y=14 },
	{ path="maps/vt/block2.png", particle_path="maps/vt/rock.png", tile_x=81, tile_y=13 },
	{ path="maps/vt/block2.png", particle_path="maps/vt/rock.png", tile_x=81, tile_y=14 },
	{ path="maps/vt/block1.png", particle_path="maps/vt/rock.png", tile_x=77, tile_y=15 },
	{ path="maps/vt/block1.png", particle_path="maps/vt/rock.png", tile_x=77, tile_y=16 },
	{ path="maps/vt/block2.png", particle_path="maps/vt/rock.png", tile_x=78, tile_y=15 },
	{ path="maps/vt/block2.png", particle_path="maps/vt/rock.png", tile_x=78, tile_y=16 },
	{ path="maps/vt/block1.png", particle_path="maps/vt/rock.png", tile_x=79, tile_y=15 },
	{ path="maps/vt/block1.png", particle_path="maps/vt/rock.png", tile_x=79, tile_y=16 },
	{ path="maps/vt/block1.png", particle_path="maps/vt/rock.png", tile_x=79, tile_y=17 },
	{ path="maps/vt/block2.png", particle_path="maps/vt/rock.png", tile_x=80, tile_y=15 },
	{ path="maps/vt/block2.png", particle_path="maps/vt/rock.png", tile_x=80, tile_y=16 },
	{ path="maps/vt/block2.png", particle_path="maps/vt/rock.png", tile_x=80, tile_y=17 },
	{ path="maps/vt/block1.png", particle_path="maps/vt/rock.png", tile_x=81, tile_y=15 },
	{ path="maps/vt/block1.png", particle_path="maps/vt/rock.png", tile_x=81, tile_y=16 },
	{ path="maps/vt/block1.png", particle_path="maps/vt/rock.png", tile_x=81, tile_y=17 },
	{ path="maps/vt/block1.png", particle_path="maps/vt/rock.png", tile_x=81, tile_y=18 },
	{ path="maps/vt/block2.png", particle_path="maps/vt/rock.png", tile_x=82, tile_y=15 },
	{ path="maps/vt/block2.png", particle_path="maps/vt/rock.png", tile_x=82, tile_y=16 },
	{ path="maps/vt/block2.png", particle_path="maps/vt/rock.png", tile_x=82, tile_y=17 },
	{ path="maps/vt/block2.png", particle_path="maps/vt/rock.png", tile_x=82, tile_y=18 },
	{ path="maps/vt/block1.png", particle_path="maps/vt/rock.png", tile_x=55, tile_y=4 },
	{ path="maps/vt/block2.png", particle_path="maps/vt/rock.png", tile_x=56, tile_y=4 },
	{ path="maps/vt/block1.png", particle_path="maps/vt/rock.png", tile_x=111, tile_y=13 },
	{ path="maps/vt/block1.png", particle_path="maps/vt/rock.png", tile_x=111, tile_y=14 },
	{ path="maps/vt/block2.png", particle_path="maps/vt/rock.png", tile_x=112, tile_y=13 },
	{ path="maps/vt/block2.png", particle_path="maps/vt/rock.png", tile_x=112, tile_y=14 },
	{ path="maps/vt/block1.png", particle_path="maps/vt/rock.png", tile_x=101, tile_y=9 },
	{ path="maps/vt/block1.png", particle_path="maps/vt/rock.png", tile_x=101, tile_y=10 },
	{ path="maps/vt/block2.png", particle_path="maps/vt/rock.png", tile_x=102, tile_y=9 },
	{ path="maps/vt/block2.png", particle_path="maps/vt/rock.png", tile_x=102, tile_y=10 },
	{ path="maps/vt/block3.png", particle_path="maps/vt/rock.png", drops_ring=true, tile_x=87, tile_y=3 },
	{ path="maps/vt/block3.png", particle_path="maps/vt/rock.png", drops_ring=true, tile_x=87, tile_y=4 },
	{ path="maps/vt/block4.png", particle_path="maps/vt/rock.png", tile_x=106, tile_y=7 },
	{ path="maps/vt/block4.png", particle_path="maps/vt/rock.png", tile_x=107, tile_y=7 }
]
bridge = [
	{ path="maps/vt/bridge.png", particle_path="maps/vt/rock.png", leftx=1616, rightx=1839, y=320 },
	{ path="maps/vt/bridge.png", particle_path="maps/vt/rock.png", leftx=1568, rightx=1615, y=112 }
]
fire = [
	{ x=168, y=88, direction="left" },
	{ x=232, y=120, direction="left" },
	{ x=280, y=152, direction="left" },
	{ x=792, y=136, direction="left" },
	{ x=904, y=168, direction="left" },
	{ x=336, y=216, direction="right" },
	{ x=736, y=104, direction="right" },
	{ x=736, y=168, direction="right" },
	{ x=960, y=184, direction="right" }
]
item_box = [
	{ x=1880, y=272, number=29, item_name="  chaos  \n emerald " }
]
level_transition = [
	{ path="maps/vt/vt1", top=48, bottom=112, left=0, right=2 }
]
map_transition = [
	{ selection=3, top=48, bottom=112, left=1966, right=1968 }
]

[objects.default]
bat_robot = [
	{ x=460, y=256 },
	{ x=508, y=256 },
	{ x=652, y=112 },
	{ x=748, y=16 },
	{ x=940, y=16 },
	{ x=1228, y=112 },
	{ x=1676, y=144 },
	{ x=1724, y=144 },
	{ x=1452, y=32 },
	{ x=1452, y=128 }
]
drill_mole = [
	{ x=692, y=54 },
	{ x=1524, y=38 }
]
flame = [
	{ x=508, y=368 },
	{ x=828, y=272 },
	{ x=1260, y=320 },
	{ x=1436, y=320 }
]
nezu = [
	{ x=920, y=224 },
	{ tile_x=67, tile_y=3 },
	{ tile_x=68, tile_y=7 },
	{ tile_x=72, tile_y=14 },
	{ tile_x=97, tile_y=19 },
	{ tile_x=104, tile_y=6 }
]
