regular_bomb = "regular bomb"
triple_bomb = "triple bomb"
large_bomb = "large bomb"
wrench = "wrench"
remote_bomb = "remote bomb"
helmet = "helmet"
napalm_bomb = "napalm bomb"
remote_robot = "remote robot"
hammer = "hammer"
super_glove = "super glove"
teleport_device = "teleport device"
fang = "fang"
night_vision = "night vision"
knuckles = "knuckles"
speed_boots = "speed boots"
sonic = "sonic"
item_radar = "item radar"
radio = "radio"

purple_emerald = "purple c. emerald"
red_emerald = "red c. emerald"
blue_emerald = "blue c. emerald"
white_emerald = "white c. emerald"
green_emerald = "green c. emerald"
yellow_emerald = "yellow c. emerald"

vulcan_gun = "vulcan gun"
anti_air_missile = "anti-air missile"
proton_torpedo = "proton torpedo"
spark = "spark"
extra_speed = "extra speed"
mine = "mine"
extra_armor = "extra armor"
rocket_booster = "rocket booster"

