[level]
music = "sound/lc.vgm"
mode = "seafox_ground"
water_level = 96
spawn = [
	{ x=64, y=538 }
]

[objects.static]
map_transition = [
	{ selection=2, seafox=true, top=0, bottom=640, left=0, right=2 }
]

[objects.default]
wood = [
	{ tile_x=27, tile_y=30, offset_x=8 },
	{ tile_x=34, tile_y=28, offset_x=8 },
	{ tile_x=40, tile_y=28, offset_x=8 },
	{ tile_x=51, tile_y=22, offset_x=8 },
	{ tile_x=66, tile_y=20, offset_x=8 },
]

