[level]
music = "sound/vt.vgm"
spawn = [
	{ x=-4, y=89 },
	{ x=-4, y=1833, previous="maps/ci/ci3" }
]

[objects.static]
breakable_block = [
	{ tile_x=23, tile_y=10, path="maps/vt/block3.png", particle_path="maps/vt/rock.png", drops_ring=true },
	{ tile_x=23, tile_y=11, path="maps/vt/block3.png", particle_path="maps/vt/rock.png", drops_ring=true },
	{ tile_x=13, tile_y=34, path="maps/vt/block3.png", particle_path="maps/vt/rock.png", drops_ring=true },
	{ tile_x=14, tile_y=34, path="maps/vt/block3.png", particle_path="maps/vt/rock.png", drops_ring=true },
	{ tile_x=4, tile_y=33, path="maps/vt/block1.png", particle_path="maps/vt/rock.png" },
	{ tile_x=4, tile_y=34, path="maps/vt/block1.png", particle_path="maps/vt/rock.png" },
	{ tile_x=5, tile_y=33, path="maps/vt/block2.png", particle_path="maps/vt/rock.png" },
	{ tile_x=5, tile_y=34, path="maps/vt/block2.png", particle_path="maps/vt/rock.png" },
	{ tile_x=15, tile_y=77, path="maps/vt/block1.png", particle_path="maps/vt/rock.png" },
	{ tile_x=16, tile_y=77, path="maps/vt/block2.png", particle_path="maps/vt/rock.png" },
	{ tile_x=11, tile_y=93, path="maps/vt/block1.png", particle_path="maps/vt/rock.png" },
	{ tile_x=11, tile_y=94, path="maps/vt/block1.png", particle_path="maps/vt/rock.png" },
	{ tile_x=12, tile_y=93, path="maps/vt/block2.png", particle_path="maps/vt/rock.png" },
	{ tile_x=12, tile_y=94, path="maps/vt/block2.png", particle_path="maps/vt/rock.png" },
	{ tile_x=13, tile_y=69, path="maps/vt/block3.png", particle_path="maps/vt/rock.png", drops_ring=true },
	{ tile_x=13, tile_y=70, path="maps/vt/block3.png", particle_path="maps/vt/rock.png", drops_ring=true },
	{ tile_x=13, tile_y=71, path="maps/vt/block3.png", particle_path="maps/vt/rock.png", drops_ring=true },
	{ tile_x=19, tile_y=110, path="maps/vt/block3.png", particle_path="maps/vt/rock.png", drops_ring=true },
	{ tile_x=19, tile_y=111, path="maps/vt/block3.png", particle_path="maps/vt/rock.png", drops_ring=true },
	{ tile_x=18, tile_y=112, path="maps/vt/block3.png", particle_path="maps/vt/rock.png", drops_ring=true },
	{ tile_x=18, tile_y=113, path="maps/vt/block3.png", particle_path="maps/vt/rock.png", drops_ring=true },
	{ tile_x=17, tile_y=114, path="maps/vt/block3.png", particle_path="maps/vt/rock.png", drops_ring=true },
	{ tile_x=17, tile_y=115, path="maps/vt/block3.png", particle_path="maps/vt/rock.png", drops_ring=true }
]
bridge = [
	{ path="maps/vt/bridge.png", particle_path="maps/vt/rock.png", leftx=32, rightx=143, y=496 },
	{ path="maps/vt/bridge.png", particle_path="maps/vt/rock.png", leftx=208, rightx=287, y=496 },
	{ path="maps/vt/bridge.png", particle_path="maps/vt/rock.png", leftx=64, rightx=95, y=1024 },
	{ path="maps/vt/bridge.png", particle_path="maps/vt/rock.png", leftx=208, rightx=255, y=1520 },
	{ path="maps/vt/bridge.png", particle_path="maps/vt/rock.png", leftx=208, rightx=255, y=1568 }
]
conveyor_belt = [
	{ top=1232, bottom=1248, left=160, right=240 },
	{ top=1296, bottom=1312, left=112, right=176 },
	{ top=1312, bottom=1328, left=176, right=208 },
	{ top=1216, bottom=1232, left=336, right=384 },
	{ top=1264, bottom=1280, left=352, right=400, flip=true },
	{ top=1312, bottom=1328, left=336, right=384 },
	{ top=1360, bottom=1376, left=352, right=400, flip=true }
]
item_box = [
	{ tile_x=8, tile_y=97, number=13, item_name=" napalm \n  bomb  " }
]
level_transition = [
	{ path="maps/ci/ci1", top=64, left=0, bottom=128, right=2 },
	{ path="maps/ci/ci3", top=1808, left=0, bottom=1872, right=2 }
]
wind = [
	{ top=512, left=352, bottom=736, right=384, xsp=0, ysp=-2 },
	{ top=688, left=304, bottom=736, right=352, xsp=2, ysp=0 },
	{ top=576, left=64, bottom=832, right=96, xsp=0, ysp=2 },
	{ top=672, left=176, bottom=832, right=208, xsp=0, ysp=-2 },
	{ top=1472, left=320, bottom=1936, right=400, xsp=0, ysp=-2 },
	{ top=1904, left=288, bottom=1936, right=368, xsp=2, ysp=0 }
]

[objects.default]
bat_robot = [
	{ x=220, y=112 },
	{ x=268, y=144 },
	{ x=252, y=240 },
	{ x=300, y=320 },
	{ x=268, y=432 },
	{ x=172, y=608 },
	{ x=252, y=608 },
	{ x=204, y=976 },
	{ x=124, y=992 },
	{ x=268, y=1408 },
	{ x=156, y=1680 },
	{ x=188, y=1744 },
	{ x=236, y=1712 }
]
drill_mole = [
	{ x=164, y=470 },
	{ x=260, y=1014 },
	{ x=116, y=1030 },
	{ x=68, y=1142 },
	{ x=292, y=1206 }
]
nezu = [
	{ tile_x=22, tile_y=11 },
	{ tile_x=15, tile_y=33 },
	{ tile_x=4, tile_y=32 },
	{ tile_x=16, tile_y=56 },
	{ tile_x=12, tile_y=71 },
	{ tile_x=15, tile_y=84 },
	{ tile_x=22, tile_y=79 },
	{ tile_x=23, tile_y=82 },
	{ tile_x=22, tile_y=85 },
	{ tile_x=8, tile_y=120 },
	{ tile_x=14, tile_y=120 }
]
