[level]
music = "sound/cc.vgm"
spawn = [
	{ x=205, y=73 },
]

[objects.static]
level_transition = [
	{ path="maps/cc/cc1", left=112, top=0, right=256, bottom=48 },
]
remote_robot_blocker = [
	{ tile_x=33, tile_y=5, offset_x=-3 },
	{ tile_x=41, tile_y=5, offset_x=-3 },
	{ tile_x=45, tile_y=5, offset_x=-3 },
	{ tile_x=31, tile_y=9, offset_x=-3 },
	{ tile_x=37, tile_y=9, offset_x=-3 },
]
heavy_gun = [
	{ tile_x=36, tile_y=26, offset_x=-4, offset_y=-4 },
	{ tile_x=41, tile_y=25, offset_x=-4, offset_y=-4 },
	{ tile_x=46, tile_y=26, offset_x=-4, offset_y=-4 },
	
	{ tile_x=5, tile_y=44, offset_x=-4, offset_y=-4 },
	{ tile_x=8, tile_y=48, offset_x=-4, offset_y=-4 },
	{ tile_x=16, tile_y=48, offset_x=-12, offset_y=-4, flip=true },
	{ tile_x=19, tile_y=44, offset_x=-12, offset_y=-4, flip=true },
]
breakable_block = [
	{ tile_x=8, tile_y=11, path="maps/cc/block1.png", particle_path="maps/cc/rock.png" },
	{ tile_x=9, tile_y=11, path="maps/cc/block3.png", particle_path="maps/cc/rock.png" },
	{ tile_x=10, tile_y=11, path="maps/cc/block3.png", particle_path="maps/cc/rock.png" },
	{ tile_x=11, tile_y=11, path="maps/cc/block3.png", particle_path="maps/cc/rock.png" },
	{ tile_x=12, tile_y=11, path="maps/cc/block2.png", particle_path="maps/cc/rock.png" },
	
	{ tile_x=30, tile_y=14, path="maps/cc/block1.png", particle_path="maps/cc/rock.png" },
	{ tile_x=31, tile_y=14, path="maps/cc/block3.png", particle_path="maps/cc/rock.png" },
	{ tile_x=32, tile_y=14, path="maps/cc/block2.png", particle_path="maps/cc/rock.png" },
	{ tile_x=30, tile_y=15, path="maps/cc/block1.png", particle_path="maps/cc/rock.png" },
	{ tile_x=31, tile_y=15, path="maps/cc/block3.png", particle_path="maps/cc/rock.png" },
	{ tile_x=32, tile_y=15, path="maps/cc/block2.png", particle_path="maps/cc/rock.png" },
	{ tile_x=30, tile_y=16, path="maps/cc/block1.png", particle_path="maps/cc/rock.png" },
	{ tile_x=31, tile_y=16, path="maps/cc/block3.png", particle_path="maps/cc/rock.png" },
	{ tile_x=32, tile_y=16, path="maps/cc/block2.png", particle_path="maps/cc/rock.png" },
	{ tile_x=30, tile_y=17, path="maps/cc/block1.png", particle_path="maps/cc/rock.png" },
	{ tile_x=31, tile_y=17, path="maps/cc/block3.png", particle_path="maps/cc/rock.png" },
	{ tile_x=32, tile_y=17, path="maps/cc/block2.png", particle_path="maps/cc/rock.png" },
	
	{ tile_x=34, tile_y=27, path="maps/cc/block3.png", particle_path="maps/cc/rock.png" },
	{ tile_x=34, tile_y=28, path="maps/cc/block3.png", particle_path="maps/cc/rock.png" },
	
	{ tile_x=48, tile_y=27, path="maps/cc/block1.png", particle_path="maps/cc/rock.png" },
	{ tile_x=49, tile_y=27, path="maps/cc/block3.png", particle_path="maps/cc/rock.png" },
	{ tile_x=50, tile_y=27, path="maps/cc/block3.png", particle_path="maps/cc/rock.png" },
	{ tile_x=51, tile_y=27, path="maps/cc/block3.png", particle_path="maps/cc/rock.png" },
	{ tile_x=52, tile_y=27, path="maps/cc/block2.png", particle_path="maps/cc/rock.png" },
	{ tile_x=48, tile_y=28, path="maps/cc/block1.png", particle_path="maps/cc/rock.png" },
	{ tile_x=49, tile_y=28, path="maps/cc/block3.png", particle_path="maps/cc/rock.png" },
	{ tile_x=50, tile_y=28, path="maps/cc/block3.png", particle_path="maps/cc/rock.png" },
	{ tile_x=51, tile_y=28, path="maps/cc/block3.png", particle_path="maps/cc/rock.png" },
	{ tile_x=52, tile_y=28, path="maps/cc/block2.png", particle_path="maps/cc/rock.png" },
	
	{ tile_x=14, tile_y=35, path="maps/cc/block1.png", particle_path="maps/cc/rock.png" },
	{ tile_x=15, tile_y=35, path="maps/cc/block2.png", particle_path="maps/cc/rock.png" },
	{ tile_x=14, tile_y=36, path="maps/cc/block1.png", particle_path="maps/cc/rock.png" },
	{ tile_x=15, tile_y=36, path="maps/cc/block2.png", particle_path="maps/cc/rock.png" },
	{ tile_x=14, tile_y=37, path="maps/cc/block1.png", particle_path="maps/cc/rock.png" },
	{ tile_x=15, tile_y=37, path="maps/cc/block2.png", particle_path="maps/cc/rock.png" },
	
	{ tile_x=10, tile_y=49, path="maps/cc/block1.png", particle_path="maps/cc/rock.png" },
	{ tile_x=11, tile_y=49, path="maps/cc/block3.png", particle_path="maps/cc/rock.png" },
	{ tile_x=12, tile_y=49, path="maps/cc/block3.png", particle_path="maps/cc/rock.png" },
	{ tile_x=13, tile_y=49, path="maps/cc/block3.png", particle_path="maps/cc/rock.png" },
	{ tile_x=14, tile_y=49, path="maps/cc/block2.png", particle_path="maps/cc/rock.png" },
	
	{ tile_x=48, tile_y=51, path="maps/cc/block1.png", particle_path="maps/cc/rock.png" },
	{ tile_x=49, tile_y=51, path="maps/cc/block2.png", particle_path="maps/cc/rock.png" },
	{ tile_x=48, tile_y=52, path="maps/cc/block1.png", particle_path="maps/cc/rock.png" },
	{ tile_x=49, tile_y=52, path="maps/cc/block2.png", particle_path="maps/cc/rock.png" },
	{ tile_x=48, tile_y=53, path="maps/cc/block1.png", particle_path="maps/cc/rock.png" },
	{ tile_x=49, tile_y=53, path="maps/cc/block2.png", particle_path="maps/cc/rock.png" },
]
bridge = [
	{ leftx=48, rightx=79, y=432, path="maps/cc/bridge.png", particle_path="maps/cc/rock.png" },
	{ leftx=96, rightx=479, y=432, path="maps/cc/bridge.png", particle_path="maps/cc/rock.png" },
]
electric_barrier = [
	{ left=36, top=14, right=37, bottom=17, tile_x=41, tile_y=17, offset_x=-4, offset_y=8 },
	{ left=44, top=31, right=45, bottom=34, tile_x=43, tile_y=34, offset_x=-4, offset_y=8 },
	{ left=23, top=50, right=24, bottom=53, tile_x=21, tile_y=53, offset_x=-4, offset_y=8 },
]

[objects.default]
sniper = [
	{ tile_x=22, tile_y=32 },
	{ tile_x=33, tile_y=32 },
	{ tile_x=28, tile_y=47 },
	{ tile_x=35, tile_y=52 },
	{ tile_x=39, tile_y=52 },
	{ tile_x=46, tile_y=47 },
]

