[level]
music = "sound/cc.vgm"
spawn = [
	{ x=205, y=73 },
]

[objects.static]
level_transition = [
	{ path="maps/cc/cc1", left=112, top=0, right=256, bottom=48 },
]
remote_robot_blocker = [
	{ tile_x=33, tile_y=5, offset_x=-3 },
	{ tile_x=41, tile_y=5, offset_x=-3 },
	{ tile_x=45, tile_y=5, offset_x=-3 },
	{ tile_x=31, tile_y=9, offset_x=-3 },
	{ tile_x=37, tile_y=9, offset_x=-3 },
]
heavy_gun = [
	{ tile_x=36, tile_y=26, offset_x=-4, offset_y=-4 },
	{ tile_x=41, tile_y=25, offset_x=-4, offset_y=-4 },
	{ tile_x=46, tile_y=26, offset_x=-4, offset_y=-4 },
	
	{ tile_x=5, tile_y=44, offset_x=-4, offset_y=-4 },
	{ tile_x=8, tile_y=48, offset_x=-4, offset_y=-4 },
	{ tile_x=16, tile_y=48, offset_x=-12, offset_y=-4, flip=true },
	{ tile_x=19, tile_y=44, offset_x=-12, offset_y=-4, flip=true },
]

