[level]
music = "sound/cc.vgm"
spawn = [
	{ x=40, y=105 },
]

[objects.static]
level_transition = [
	{ path="maps/cc/cc2", left=0, top=112, right=2, bottom=144 },
]
conveyor_belt = [
	{ left=64, top=400, right=144, bottom=416 },
	{ left=176, top=400, right=256, bottom=416, flip=true },
]
breakable_block = [
	{ tile_x=18, tile_y=21, path="maps/cc/block1.png", particle_path="maps/cc/rock.png" },
	{ tile_x=19, tile_y=21, path="maps/cc/block3.png", particle_path="maps/cc/rock.png" },
]
pushable_object = [
    { tile_x=20, tile_y=2, offset_x=1, path="objects/weight.png" },
]
dr_fukurokov = [
	{ start_x=182, start_y=112, control_x=320, control_y=112, platform_x=144, platform_y=144 },
]

