[sprite]
image = "rock_thrower.png"
width = 16
height = 29

[animations.idle]
frames = [0, 1]
delay = 24

[animations.throw]
frames = [0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1]
delay = 8

