[level]
music = "sound/pm.vgm"
spawn = [
	{ x=-6, y=1913 },
	{ x=405, y=25, previous="maps/pm/pm2", flip=true },
	{ x=405, y=1097, previous="maps/pm/pm3", flip=true }
]

[objects.static]
breakable_block = [
	{ path="maps/pm/block.png", drops_ring=true, tile_x=3, tile_y=100 },
	{ path="maps/pm/block.png", drops_ring=true, tile_x=3, tile_y=101 },
	{ path="maps/pm/block.png", drops_ring=true, tile_x=3, tile_y=102 },
	{ path="maps/pm/block.png", tile_x=14, tile_y=71 },
	{ path="maps/pm/block.png", tile_x=15, tile_y=71 },
	{ path="maps/pm/block.png", tile_x=4, tile_y=26 },
	{ path="maps/pm/block.png", tile_x=5, tile_y=26 },
	{ path="maps/pm/block.png", tile_x=4, tile_y=27 },
	{ path="maps/pm/block.png", tile_x=5, tile_y=27 },
	{ path="maps/pm/block.png", tile_x=11, tile_y=27 },
	{ path="maps/pm/block.png", tile_x=12, tile_y=27 },
	{ path="maps/pm/block.png", tile_x=11, tile_y=28 },
	{ path="maps/pm/block.png", tile_x=12, tile_y=28 }
]
item_box = [
	{ x=408, y=1408, number=25, item_name="rocket_booster" },
	{ x=376, y=896, number=16, item_name="helmet" }
]
level_transition = [
	{ path="maps/pm/pm2", top=0, bottom=64, left=446, right=448 },
	{ path="maps/pm/pm3", top=1088, bottom=1136, left=446, right=448 }
]
map_transition = [
	{ selection=3, top=1888, bottom=1952, left=0, right=2 }
]
wind = [
	{ top=528, left=48, bottom=688, right=192, xsp=0, ysp=-1 },
	{ top=32, left=272, bottom=192, right=368, xsp=0, ysp=-1 }
]

[objects.default]
bomb_thrower = [
	{ x=272, y=1893, left_x=96, right_x=336 },
	{ x=368, y=1893, left_x=128, right_x=368 }
]
jumper = [
	{ x=256, y=1713 },
	{ x=176, y=1713 },
	{ x=224, y=817 },
	{ x=176, y=785 },
	{ x=128, y=753 }
]
moving_platform = [
	{ start_x=400, start_y=1936, end_x=400, end_y=1696 },
	{ start_x=336, start_y=1488, end_x=336, end_y=1392 },
	{ start_x=288, start_y=288, end_x=160, end_y=288 },
	{ start_x=192, start_y=160, end_x=224, end_y=160, idle=false }
]
rock_thrower = [
	{ x=248, y=1539 },
	{ x=288, y=1059 },
	{ x=352, y=931 },
	{ x=144, y=435 },
	{ x=272, y=451, flip=true },
	{ x=368, y=307 },
	{ x=64, y=227, flip=true }
]
strong_wind = [
	{ top=1360, left=96, bottom=1424, right=128 }
]
