[level]
music = "sound/pm.vgm"
spawn = [
	{ x=-4, y=41 }
]

[objects.static]
breakable_block = [
	{ path="maps/pm/block.png", tile_x=13, tile_y=13 },
	{ path="maps/pm/block.png", tile_x=14, tile_y=13 },
	{ path="maps/pm/block.png", tile_x=15, tile_y=13 },
	{ path="maps/pm/block.png", tile_x=16, tile_y=13 },
	{ path="maps/pm/block.png", tile_x=13, tile_y=14 },
	{ path="maps/pm/block.png", tile_x=14, tile_y=14 },
	{ path="maps/pm/block.png", tile_x=13, tile_y=15 },
	{ path="maps/pm/block.png", tile_x=30, tile_y=3 },
	{ path="maps/pm/block.png", tile_x=30, tile_y=4 },
	{ path="maps/pm/block.png", tile_x=39, tile_y=3 },
	{ path="maps/pm/block.png", tile_x=40, tile_y=3 },
	{ path="maps/pm/block.png", tile_x=41, tile_y=3 },
	{ path="maps/pm/block.png", tile_x=39, tile_y=4 },
	{ path="maps/pm/block.png", tile_x=40, tile_y=4 },
	{ path="maps/pm/block.png", tile_x=41, tile_y=4 }
]
bridge = [
	{ path="maps/pm/bridge.png", particle_path="maps/pm/bridge_part.png", leftx=320, rightx=399, y=320 },
	{ path="maps/pm/bridge.png", particle_path="maps/pm/bridge_part.png", leftx=432, rightx=463, y=352 },
	{ path="maps/pm/bridge.png", particle_path="maps/pm/bridge_part.png", leftx=496, rightx=527, y=320 }
]
item_box = [
	{ x=440, y=64, number=3, item_name="teleport_device" }
]
level_transition = [
	{ path="maps/pm/pm1", top=0, bottom=80, left=0, right=2 }
]
map_transition = [
	{ selection=3, top=478, bottom=480, left=0, right=704 }
]
wind = [
	{ left=64, top=32, right=160, bottom=112, xsp=-1, ysp=0 },
	{ left=160, top=32, right=400, bottom=208, xsp=-1, ysp=0 },
	{ left=16, top=288, right=112, bottom=384, xsp=0, ysp=-1 },
	{ left=272, top=256, right=528, bottom=320, xsp=-0.8, ysp=0.8 },
	{ left=288, top=336, right=400, bottom=432, xsp=-1, ysp=1 }
]

[objects.default]
jumper = [
	{ x=32, y=209 },
	{ x=80, y=209 }
]
rock_thrower = [
	{ x=384, y=51 },
	{ x=512, y=147, flip=true },
	{ x=592, y=99 },
	{ x=512, y=51, flip=true }
]
strong_wind = [
	{ left=592, top=432, right=624, bottom=480 }
]
