spark = " spark  \n        "
speed_boots = " speed  \n boots  "
radio = " radio  \n        "
chaos_emerald = "  chaos  \n emerald "
remote_robot = " remote \n robot  "
hammer = " hammer \n        "
remote_bomb = " remote \n  bomb  "
rocket_booster = " rocket  \n booster "
helmet = " helmet \n        "
teleport_device = " teleport \n  device  "
super_glove = "  super  \n  glove  "
mine = "  mine  \n        "
napalm_bomb = " napalm \n  bomb  "
anti_air_missile = " anti-air \n missile  "
triple_bomb = " triple \n  bomb  "
sonic = " sonic \n       "
proton_torpedo = " proton  \n torpedo "
extra_speed = "  extra  \n  speed  "

