[level]
music = "sound/cf.vgm"
spawn = [
	{ x=-2, y=585 },
	{ x=1172, y=232, previous="maps/cf/cf2", flip=true }
]

[objects.static]
breakable_block = [
	{ tile_x=9, tile_y=4, path="maps/cf/cf_block.png" },
	{ tile_x=10, tile_y=4, path="maps/cf/cf_block.png" }
]
grass_block = [
	{ tile_x=28, tile_y=35, path="maps/cf/cf_grass.png" },
	{ tile_x=28, tile_y=36, path="maps/cf/cf_grass.png" },
	{ tile_x=31, tile_y=34, path="maps/cf/cf_grass.png" },
	{ tile_x=31, tile_y=35, path="maps/cf/cf_grass.png" },
	{ tile_x=31, tile_y=36, path="maps/cf/cf_grass.png" },
	{ tile_x=32, tile_y=34, path="maps/cf/cf_grass.png" },
	{ tile_x=32, tile_y=35, path="maps/cf/cf_grass.png" },
	{ tile_x=32, tile_y=36, path="maps/cf/cf_grass.png" },
	{ tile_x=33, tile_y=34, path="maps/cf/cf_grass.png" },
	{ tile_x=33, tile_y=35, path="maps/cf/cf_grass.png" },
	{ tile_x=33, tile_y=36, path="maps/cf/cf_grass.png" },
	{ tile_x=47, tile_y=33, path="maps/cf/cf_grass.png" },
	{ tile_x=47, tile_y=34, path="maps/cf/cf_grass.png" },
	{ tile_x=51, tile_y=34, path="maps/cf/cf_grass.png" },
	{ tile_x=51, tile_y=35, path="maps/cf/cf_grass.png" }
]
item_box = [
	{ tile_x=3, tile_y=2, number=32, item_name="chaos_emerald" },
	{ x=776, y=256, number=14, item_name="triple_bomb" }
]
level_transition = [
	{ path="maps/cf/cf2", top=224, bottom=272, left=1214, right=1216 }
]
map_transition = [
	{ selection=5, top=512, bottom=624, left=0, right=2 }
]
pushable_object = [
	{ x=1112, y=320, path="objects/rock.png" }
]
pushable_spring = [
	{ x=424, y=432 },
	{ x=664, y=256 },
	{ x=360, y=208 }
]
wind = [
	{ top=384, left=672, bottom=416, right=736, xsp=0, ysp=1 },
	{ top=384, left=864, bottom=448, right=1056, xsp=0, ysp=1 },
	{ top=192, left=816, bottom=304, right=1072, xsp=-1, ysp=0 },
	{ top=160, left=512, bottom=256, right=560, xsp=-0, ysp=1 }
]
