video = "video"
controls = "controls"
sound = "sound"
on = "on"
off = "off"

resolution = "resolution"
pixel_ar = "pixel ar"
pixel_ar_gg = "gg"
scale_mode = "scale mode"
scale_mode_smooth = "smooth"
scale_mode_sharp = "sharp"
vsync = "v-sync"
vsync_adapt = "adapt"
window_size = "window size"

map_keyboard = "map keyboard"
map_gamepad = "map gamepad"
rumble = "rumble"
hide_onscreen = "hide onscreen"

button_up = "up"
button_down = "down"
button_left = "left"
button_right = "right"
button_a = "a"
button_b = "b"
button_lb = "lb"
button_rb = "rb"
button_start = "start"

main = "main"
music = "music"
sfx = "sfx"

