[level]
music = "sound/pf.vgm"
spawn = [
	{ x=-7, y=345, previous="maps/pf/pf2" }
]

[objects.static]
bird_walker = [
	{ floor_y=175 }
]
item_box = [
	{ x=888, y=112, number=6, item_name=" remote \n robot  " }
]
level_transition = [
	{ path="maps/pf/pf2", top=0, bottom=384, left=0, right=2 }
]
map_transition = [
	{ selection=2, top=0, bottom=160, left=958, right=960 }
]
